version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: fynnel_prod
    command: node dist/index.js
    ports:
      - "80:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:17-alpine3.22
    container_name: postgres_fynnel_prod
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

volumes:
  postgres_prod_data:

