version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fynnel_dev
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_fynnel_dev
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: development
      POSTGRES_PASS: devenv123
      POSTGRES_DB: fynnel_dev
    ports:
      - "5432:5432"
    volumes:
      - "postgres_dev_data:/var/lib/postgresql/data"
    shm_size: "128m"

volumes:
  postgres_dev_data:
