# build stage
FROM node:20 AS builder

WORKDIR /usr/src/app
COPY package*.json  ./

RUN npm install
COPY . .

RUN npm run build

FROM node:20

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --only=production

COPY --from=builder /usr/src/app/dist ./dist
COPY prisma ./prisma

EXPOSE 3000
CMD ["node", "dist/index.js"]

